apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hpf0rzdul-go
  janus-idp.io/tekton: hpf0rzdul-go
  backstage.io/kubernetes-id: hpf0rzdul-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hpf0rzdul-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
